In [78]:
import numpy as np
distance = np.load('distance_ALMI_800+164_not_random_dtw_matrix.npy')
y_data = np.load('y_data_ALMI_800+164_not_random_dtw_matrix.npy')

In [79]:
t = np.array(distance).reshape(distance.shape[0],12,12,1)
print(t.shape)

(964, 12, 12, 1)


In [107]:
t = np.concatenate((t[:300],t[800:]),axis=0)
y_data = np.concatenate((y_data[:300],y_data[800:]),axis=0)

In [108]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import scale
from tensorflow.keras.layers import Flatten, Activation
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import tensorflow.keras.backend as K
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D, AvgPool2D

In [109]:
y_train2[0:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [121]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(t[:300,:,:,:], y_data[:300],
                                                        test_size=0.25,
                                                     random_state=42)

X_train2, X_test2, y_train2, y_test2 = train_test_split(t[300:,:,:,:], y_data[300:],
                                                        test_size=0.25,
                                                     random_state=42)
                                                        
X_train = np.concatenate((X_train1, X_train2), axis=0)
X_test = np.concatenate((X_test1, X_test2), axis=0)
y_train = np.concatenate((y_train1, y_train2), axis=0)
y_test = np.concatenate((y_test1, y_test2), axis=0)

np.random.seed(42)
train_indices = np.random.permutation(len(X_train))
X_train = X_train[train_indices]
y_train = y_train[train_indices]

test_indices = np.random.permutation(len(X_test))
X_test = X_test[test_indices]
y_test = y_test[test_indices]


K.clear_session()


model = Sequential()

model.add(Conv2D(10, (3, 3), input_shape=(12, 12, 1)))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Flatten())

# model.add(Dense(1024, activation='relu'))
# model.add(Dense(512, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='BinaryCrossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.summary()

model.fit(X_train, y_train, batch_size=32,
          epochs=25, verbose=1, validation_split=0.25)
model.evaluate(X_test, y_test)




Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 10, 10, 10)        100       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 5, 5, 10)         0         
 )                                                               
                                                                 
 flatten (Flatten)           (None, 250)               0         
                                                                 
 dense (Dense)               (None, 256)               64256     
                                                                 
 dense_1 (Dense)             (None, 10)                2570      
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                        

[0.19821998476982117, 0.9396551847457886]

In [112]:
# X_train, X_test, y_train, y_test = train_test_split(t, y_data,
#                                                     test_size=0.25,
#                                                     random_state=42)

# K.clear_session()


# model = Sequential()

# model.add(Conv2D(10, (3, 3), input_shape=(12, 12, 1)))
# model.add(MaxPool2D(pool_size=(2, 2)))
# model.add(Flatten())

# model.add(Dense(1024, activation='relu'))
# # model.add(Dense(512, activation='relu'))
# model.add(Dense(256, activation='relu'))
# model.add(Dense(10, activation='relu'))
# model.add(Dense(1, activation='sigmoid'))

# model.compile(loss='BinaryCrossentropy',
#               optimizer='adam',
#               metrics=['accuracy'])

# model.summary()

# model.fit(X_train, y_train, batch_size=16,
#           epochs=25, verbose=1, validation_split=0.25)
# model.evaluate(X_test, y_test)



In [68]:
# xt = np.load(r"D:\Internship\ptb-diagnostic-ecg-database-1.0.0\Old Rocket\xt_ALMI_800+164_kernels10000.npy")
# ynew = np.load(r"D:\Internship\ptb-diagnostic-ecg-database-1.0.0\Old Rocket\ynew_ALMI_800+164_kernels10000.npy")
# patient_ids = np.load(r"D:\Internship\ptb-diagnostic-ecg-database-1.0.0\Old Rocket\patient_id_ALMI_800+164_kernels10000.npy")

In [76]:
xt = np.load(r"D:\Internship\ptb-diagnostic-ecg-database-1.0.0\Old Rocket\xt_ALMI_800+164_kernels5000.npy")
ynew = np.load(r"D:\Internship\ptb-diagnostic-ecg-database-1.0.0\Old Rocket\ynew_ALMI_800+164_kernels5000.npy")
patient_ids = np.load(r"D:\Internship\ptb-diagnostic-ecg-database-1.0.0\Old Rocket\patient_id_ALMI_800+164_kernels5000.npy")

In [69]:
distance = np.load('distance_ALMI_800+164_not_random_windowed_dtw_matrix.npy')
y_data = np.load('y_data_ALMI_800+164_not_random_windowed_dtw_matrix.npy')

In [70]:
def extract_upper_triangular(matrix):
    n = len(matrix)
    upper_triangular_array = []

    for i in range(n):
        for j in range(i, n):
            upper_triangular_array.append(matrix[i][j])

    return upper_triangular_array

def concatenate_upper_triangular_vectors(matrix1, matrix2, matrix3, matrix4):
    vector1 = extract_upper_triangular(matrix1)
    vector2 = extract_upper_triangular(matrix2)
    vector3 = extract_upper_triangular(matrix3)
    vector4 = extract_upper_triangular(matrix4)

    concatenated_vector = vector1 + vector2 + vector3 + vector4
    return concatenated_vector

t2=[]
for i in range(distance.shape[0]):
    K_i = extract_upper_triangular(distance[i])
    t2.append(K_i)
t2 = np.array(t2)
print(t2.shape)

(4820, 78)


In [71]:
xt.shape

(4820, 20000)

In [72]:
x_all = np.zeros((xt.shape[0],xt.shape[1]+78))
# k = //5
for i in range(xt.shape[0]):  
    x_all[i] = np.concatenate((xt[i], t2[i]), axis=0)

In [73]:
xt = x_all

In [74]:
xt.shape

(4820, 20078)

In [77]:
window = 5
unhealthy = 164
folds = 5

unhealthy_x = xt[:unhealthy*window]
healthy_x = xt[unhealthy*window:]
unhealthy_y = ynew[:unhealthy*window]
healthy_y = ynew[unhealthy*window:]

from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.model_selection import GroupKFold
from sklearn.linear_model import SGDClassifier
import numpy as np

gkf1 = GroupKFold(n_splits=folds)
gkf2 = GroupKFold(n_splits=folds)

sum_accuracy = 0
sum_sensitivity = 0
sum_specificity = 0
sum_f1 = 0

# for train_idx1, test_idx1,train_idx2, test_idx2  in gkf1.split(xt[:800*5], ynew[:800*5], groups=patient_ids[:800*5]),gkf2.split(xt[800*5:], ynew[800*5:], groups=patient_ids[800*5:]):
for train_idx1, test_idx1  in gkf1.split(xt[:unhealthy*window], ynew[:unhealthy*window], groups=patient_ids[:unhealthy*window]):
    sum_accuracy = 0
    X_train1, X_test1 = xt[train_idx1], xt[test_idx1]
    y_train1, y_test1 = ynew[train_idx1], ynew[test_idx1]

    for train_idx2, test_idx2  in gkf2.split(xt[unhealthy*window:], ynew[unhealthy*window:], groups=patient_ids[unhealthy*window:]):
        X_train2, X_test2 = healthy_x[train_idx2], healthy_x[test_idx2]
        y_train2, y_test2 = healthy_y[train_idx2], healthy_y[test_idx2]

        X_train = np.concatenate((X_train1, X_train2), axis=0) 
        X_test = np.concatenate((X_test1, X_test2), axis=0) 

        y_train = np.concatenate((y_train1, y_train2), axis=0) 
        y_test = np.concatenate((y_test1, y_test2), axis=0)
        
    # for train_idx, test_idx in gkf.split(xt, ynew, groups=patient_ids):
    #     X_train, X_test = xt.iloc[train_idx], xt.iloc[test_idx]
    #     y_train, y_test = ynew[train_idx], ynew[test_idx]

        classifier = SGDClassifier()
        classifier.fit(X_train, y_train)

        y_pred = classifier.predict(X_test)
        
        y_pred_majority = []
        for i in range(0, y_pred.shape[0], window):
            majority_vote = np.bincount(y_pred[i:i+window]).argmax()
            y_pred_majority.append(majority_vote)

        y_test_majority = []
        for i in range(0, y_test.shape[0], window):
            majority_vote = np.bincount(y_test[i:i+window]).argmax()
            y_test_majority.append(majority_vote)

        accuracy = accuracy_score(y_test_majority, y_pred_majority)
        sum_accuracy += accuracy

    #     tn, fp, fn, tp = confusion_matrix(y_test_majority, y_pred_majority).ravel()

    #     sensitivity = tp / (tp + fn)
    #     specificity = tn / (tn + fp)
    #     f1 = f1_score(y_test_majority, y_pred_majority)

    #     sum_sensitivity += sensitivity
    #     sum_specificity += specificity
    #     sum_f1 += f1

        print(confusion_matrix(y_test_majority, y_pred_majority))
        print("Accuracy:", accuracy)
    #     print("Sensitivity:", sensitivity)
    #     print("Specificity:", specificity)
    #     print("F1-Score:", f1)
    #     print()

    average_accuracy = sum_accuracy / folds
    # average_sensitivity = sum_sensitivity / 5
    # average_specificity = sum_specificity / 5
    # average_f1 = sum_f1 / 5

    print("Average Accuracy:", average_accuracy)
    # print("Average Sensitivity:", average_sensitivity)
    # print("Average Specificity:", average_specificity)
    # print("Average F1-Score:", average_f1)


[[ 26   7]
 [  3 157]]
Accuracy: 0.9481865284974094
[[ 28   4]
 [  3 158]]
Accuracy: 0.9637305699481865
[[ 28   4]
 [  2 159]]
Accuracy: 0.9689119170984456
[[ 29   5]
 [  0 159]]
Accuracy: 0.9740932642487047
[[ 30   3]
 [  6 154]]
Accuracy: 0.9533678756476683
Average Accuracy: 0.9616580310880829
[[ 28   5]
 [  4 156]]
Accuracy: 0.9533678756476683
[[ 28   4]
 [  0 161]]
Accuracy: 0.9792746113989638
[[ 25   7]
 [  0 161]]
Accuracy: 0.9637305699481865
[[ 32   2]
 [  2 157]]
Accuracy: 0.9792746113989638
[[ 31   2]
 [  4 156]]
Accuracy: 0.9689119170984456
Average Accuracy: 0.9689119170984457
[[ 25   8]
 [  2 158]]
Accuracy: 0.9481865284974094
[[ 28   4]
 [  1 160]]
Accuracy: 0.9740932642487047
[[ 26   6]
 [  0 161]]
Accuracy: 0.9689119170984456
[[ 31   3]
 [  0 159]]
Accuracy: 0.9844559585492227
[[ 30   3]
 [  0 160]]
Accuracy: 0.9844559585492227
Average Accuracy: 0.972020725388601
[[ 25   8]
 [  2 158]]
Accuracy: 0.9481865284974094
[[ 29   3]
 [  2 159]]
Accuracy: 0.9740932642487047
[[ 27 